config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: :delete_task

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
  end

  def show
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <h2> Edit your task </h2>

  <%= render 'form', task: @task %>
</div>

<%= link_to "go back", tasks_path  %>

app/views/tasks/index.html.erb
<body id= 'animate-area'>
  <div class="container">
    <h1> Task Manager </h1>
      <ul>
        <% @tasks.each do |task|%>
        <li> <%= link_to task.title , task_path(task), :class => 'deco' %>
          <%= link_to "💥", delete_task_path(task),
          method: :delete,
          data: { confirm: "Are you sure?" }, :class => 'deco'%>
        <% end %>
        </li>
      </ul>
     <div class="center">
        <%= link_to 'Create task', tasks_new_path, :class => "create" %>
     </div>
  </div>
</body>

app/views/tasks/new.html.erb
<div class="container">
  <h2> Create a new task </h2>

  <%= render 'form', task: @task %>
</div>

<%= link_to "go back", tasks_path  %>

app/views/tasks/show.html.erb
<div class="container">
  <h2> Detail of your task</h2>

  <ul>
    <%= @task.details%>
  </ul>
</div>

<%= link_to "go back", tasks_path  %>
<%= link_to 'Edit task', edit_task_path %>